name: great_quran
description: Great Quran.

publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:


  ##### ------------------------ UI -------------------------- #####

  loading_indicator: ^3.1.0

  extended_image: ^6.2.1

  shimmer: ^2.0.0

  flutter_spinkit: ^5.1.0

  ##### ------------------------ Data -------------------------- #####

  shared_preferences: ^2.0.15

  easy_localization: ^3.0.1

  ##### ------------------------ State & Bushiness Logic -------------------------- #####

  flutter_riverpod: ^2.1.1

  equatable: ^2.0.3

  json_annotation: ^4.3.0

  event_bus: ^2.0.0

  rxdart: ^0.27.7

  ##### ------------------------ Utilities -------------------------- #####

  overlay_support: ^2.0.1

  audioplayers: ^0.20.1

  carousel_slider: ^4.0.0

  clipboard: ^0.1.3

  share_plus: ^4.0.9

  upgrader: ^4.2.1
  
  intl: ^0.17.0

  dio: ^4.0.6

  collection: ^1.16.0

  url_launcher: ^6.0.15

  flutter_qiblah: ^2.1.0

  permission_handler: ^10.2.0

  location: ^4.4.0

  # Local Notifications Service
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  flutter_native_timezone: ^2.0.0


  ##### ------------------------ Flutter Dependencies -------------------------- #####

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  in_app_review: ^2.0.4


dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf
          

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_gravity: center
